// automatically generated by the FlatBuffers compiler, do not modify

package com.worldql.client.Messages;

public final class Instruction {
  private Instruction() { }
  public static final int Heartbeat = 0;
  public static final int Handshake = 1;
  public static final int PeerConnect = 2;
  public static final int PeerDisconnect = 3;
  public static final int AreaSubscribe = 4;
  public static final int AreaUnsubscribe = 5;
  public static final int GlobalMessage = 6;
  public static final int LocalMessage = 7;
  public static final int RecordCreate = 8;
  public static final int RecordRead = 9;
  public static final int RecordUpdate = 10;
  public static final int RecordDelete = 11;
  public static final int RecordReply = 12;
  public static final int Unknown = 255;
}

