// automatically generated by the FlatBuffers compiler, do not modify

package com.worldql.client.Messages;

public final class Instruction {
  private Instruction() { }
  public static final int Heartbeat = 0;
  public static final int Handshake = 1;
  public static final int LocalMessage = 2;
  public static final int GlobalMessage = 3;
  public static final int RecordCreate = 4;
  public static final int RecordRead = 5;
  public static final int RecordUpdate = 6;
  public static final int RecordDelete = 7;
  public static final int RecordReply = 8;
  public static final int AreaSubscribe = 9;
  public static final int AreaUnsubscribe = 10;
  public static final int Unknown = 255;
}

