name: 'WorldQLClient'
version: '0.03-alpha'
api-version: '1.17'
main: 'com.worldql.client.WorldQLClient'

commands:
  refreshworld:
    description: 'Pull and apply all block actions from database'
    usage: '/refreshworld'
    permission: 'worldqlclient.refreshworld'
    
permissions:
  worldqlclient.refreshworld:
    default: 'op'
    description: 'Allow the usage of /refreshworld'
