name: 'WorldQLClient'
version: '0.03-alpha'
description: 'A WorldQL client to spread the load of a Minecraft world across multiple Spigot servers.'

api-version: '1.17'
main: 'com.worldql.client.WorldQLClient'

commands:
  refreshworld:
    description: 'Pulls and applies all block actions from the database.'
    usage: '/refreshworld'
    permission: 'worldqlclient.refreshworld'
    
permissions:
  worldqlclient.refreshworld:
    default: 'op'
    description: 'Allows the usage of /refreshworld.'
