// automatically generated by the FlatBuffers compiler, do not modify

package com.worldql.mammoth.Messages;

public final class Replication {
  private Replication() { }
  public static final int ExceptSelf = 0;
  public static final int IncludingSelf = 1;
  public static final int OnlySelf = 2;

  public static final String[] names = { "ExceptSelf", "IncludingSelf", "OnlySelf", };

  public static String name(int e) { return names[e]; }
}

