// automatically generated by the FlatBuffers compiler, do not modify

package com.worldql.mammoth.Messages;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Vec3d extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Vec3d __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double x() { return bb.getDouble(bb_pos + 0); }
  public double y() { return bb.getDouble(bb_pos + 8); }
  public double z() { return bb.getDouble(bb_pos + 16); }

  public static int createVec3d(FlatBufferBuilder builder, double x, double y, double z) {
    builder.prep(8, 24);
    builder.putDouble(z);
    builder.putDouble(y);
    builder.putDouble(x);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Vec3d get(int j) { return get(new Vec3d(), j); }
    public Vec3d get(Vec3d obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

