// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MinecraftPlayer.proto

package com.worldql.client.compiled_protobuf;

public final class MinecraftPlayer {
  private MinecraftPlayer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float x = 1;</code>
     * @return The x.
     */
    float getX();

    /**
     * <code>float y = 2;</code>
     * @return The y.
     */
    float getY();

    /**
     * <code>float z = 3;</code>
     * @return The z.
     */
    float getZ();

    /**
     * <code>float pitch = 4;</code>
     * @return The pitch.
     */
    float getPitch();

    /**
     * <code>float yaw = 5;</code>
     * @return The yaw.
     */
    float getYaw();

    /**
     * <code>string UUID = 6;</code>
     * @return The uUID.
     */
    java.lang.String getUUID();
    /**
     * <code>string UUID = 6;</code>
     * @return The bytes for uUID.
     */
    com.google.protobuf.ByteString
        getUUIDBytes();

    /**
     * <code>string name = 7;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 7;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code PlayerState}
   */
  public static final class PlayerState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlayerState)
      PlayerStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerState.newBuilder() to construct.
    private PlayerState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerState() {
      uUID_ = "";
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerState();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              x_ = input.readFloat();
              break;
            }
            case 21: {

              y_ = input.readFloat();
              break;
            }
            case 29: {

              z_ = input.readFloat();
              break;
            }
            case 37: {

              pitch_ = input.readFloat();
              break;
            }
            case 45: {

              yaw_ = input.readFloat();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              uUID_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.worldql.client.compiled_protobuf.MinecraftPlayer.internal_static_PlayerState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.worldql.client.compiled_protobuf.MinecraftPlayer.internal_static_PlayerState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.class, com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private float x_;
    /**
     * <code>float x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_;
    /**
     * <code>float y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public float getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private float z_;
    /**
     * <code>float z = 3;</code>
     * @return The z.
     */
    @java.lang.Override
    public float getZ() {
      return z_;
    }

    public static final int PITCH_FIELD_NUMBER = 4;
    private float pitch_;
    /**
     * <code>float pitch = 4;</code>
     * @return The pitch.
     */
    @java.lang.Override
    public float getPitch() {
      return pitch_;
    }

    public static final int YAW_FIELD_NUMBER = 5;
    private float yaw_;
    /**
     * <code>float yaw = 5;</code>
     * @return The yaw.
     */
    @java.lang.Override
    public float getYaw() {
      return yaw_;
    }

    public static final int UUID_FIELD_NUMBER = 6;
    private volatile java.lang.Object uUID_;
    /**
     * <code>string UUID = 6;</code>
     * @return The uUID.
     */
    @java.lang.Override
    public java.lang.String getUUID() {
      java.lang.Object ref = uUID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uUID_ = s;
        return s;
      }
    }
    /**
     * <code>string UUID = 6;</code>
     * @return The bytes for uUID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUUIDBytes() {
      java.lang.Object ref = uUID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uUID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 7;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 7;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0F) {
        output.writeFloat(1, x_);
      }
      if (y_ != 0F) {
        output.writeFloat(2, y_);
      }
      if (z_ != 0F) {
        output.writeFloat(3, z_);
      }
      if (pitch_ != 0F) {
        output.writeFloat(4, pitch_);
      }
      if (yaw_ != 0F) {
        output.writeFloat(5, yaw_);
      }
      if (!getUUIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, uUID_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x_);
      }
      if (y_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y_);
      }
      if (z_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, z_);
      }
      if (pitch_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, pitch_);
      }
      if (yaw_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, yaw_);
      }
      if (!getUUIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, uUID_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState)) {
        return super.equals(obj);
      }
      com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState other = (com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState) obj;

      if (java.lang.Float.floatToIntBits(getX())
          != java.lang.Float.floatToIntBits(
              other.getX())) return false;
      if (java.lang.Float.floatToIntBits(getY())
          != java.lang.Float.floatToIntBits(
              other.getY())) return false;
      if (java.lang.Float.floatToIntBits(getZ())
          != java.lang.Float.floatToIntBits(
              other.getZ())) return false;
      if (java.lang.Float.floatToIntBits(getPitch())
          != java.lang.Float.floatToIntBits(
              other.getPitch())) return false;
      if (java.lang.Float.floatToIntBits(getYaw())
          != java.lang.Float.floatToIntBits(
              other.getYaw())) return false;
      if (!getUUID()
          .equals(other.getUUID())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getX());
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getY());
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getZ());
      hash = (37 * hash) + PITCH_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPitch());
      hash = (37 * hash) + YAW_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getYaw());
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUUID().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerState)
        com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.worldql.client.compiled_protobuf.MinecraftPlayer.internal_static_PlayerState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.worldql.client.compiled_protobuf.MinecraftPlayer.internal_static_PlayerState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.class, com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.Builder.class);
      }

      // Construct using com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        x_ = 0F;

        y_ = 0F;

        z_ = 0F;

        pitch_ = 0F;

        yaw_ = 0F;

        uUID_ = "";

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.worldql.client.compiled_protobuf.MinecraftPlayer.internal_static_PlayerState_descriptor;
      }

      @java.lang.Override
      public com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState getDefaultInstanceForType() {
        return com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.getDefaultInstance();
      }

      @java.lang.Override
      public com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState build() {
        com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState buildPartial() {
        com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState result = new com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState(this);
        result.x_ = x_;
        result.y_ = y_;
        result.z_ = z_;
        result.pitch_ = pitch_;
        result.yaw_ = yaw_;
        result.uUID_ = uUID_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState) {
          return mergeFrom((com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState other) {
        if (other == com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.getDefaultInstance()) return this;
        if (other.getX() != 0F) {
          setX(other.getX());
        }
        if (other.getY() != 0F) {
          setY(other.getY());
        }
        if (other.getZ() != 0F) {
          setZ(other.getZ());
        }
        if (other.getPitch() != 0F) {
          setPitch(other.getPitch());
        }
        if (other.getYaw() != 0F) {
          setYaw(other.getYaw());
        }
        if (!other.getUUID().isEmpty()) {
          uUID_ = other.uUID_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float x_ ;
      /**
       * <code>float x = 1;</code>
       * @return The x.
       */
      @java.lang.Override
      public float getX() {
        return x_;
      }
      /**
       * <code>float x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(float value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>float y = 2;</code>
       * @return The y.
       */
      @java.lang.Override
      public float getY() {
        return y_;
      }
      /**
       * <code>float y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(float value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        
        y_ = 0F;
        onChanged();
        return this;
      }

      private float z_ ;
      /**
       * <code>float z = 3;</code>
       * @return The z.
       */
      @java.lang.Override
      public float getZ() {
        return z_;
      }
      /**
       * <code>float z = 3;</code>
       * @param value The z to set.
       * @return This builder for chaining.
       */
      public Builder setZ(float value) {
        
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float z = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearZ() {
        
        z_ = 0F;
        onChanged();
        return this;
      }

      private float pitch_ ;
      /**
       * <code>float pitch = 4;</code>
       * @return The pitch.
       */
      @java.lang.Override
      public float getPitch() {
        return pitch_;
      }
      /**
       * <code>float pitch = 4;</code>
       * @param value The pitch to set.
       * @return This builder for chaining.
       */
      public Builder setPitch(float value) {
        
        pitch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float pitch = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPitch() {
        
        pitch_ = 0F;
        onChanged();
        return this;
      }

      private float yaw_ ;
      /**
       * <code>float yaw = 5;</code>
       * @return The yaw.
       */
      @java.lang.Override
      public float getYaw() {
        return yaw_;
      }
      /**
       * <code>float yaw = 5;</code>
       * @param value The yaw to set.
       * @return This builder for chaining.
       */
      public Builder setYaw(float value) {
        
        yaw_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float yaw = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearYaw() {
        
        yaw_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object uUID_ = "";
      /**
       * <code>string UUID = 6;</code>
       * @return The uUID.
       */
      public java.lang.String getUUID() {
        java.lang.Object ref = uUID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uUID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string UUID = 6;</code>
       * @return The bytes for uUID.
       */
      public com.google.protobuf.ByteString
          getUUIDBytes() {
        java.lang.Object ref = uUID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uUID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string UUID = 6;</code>
       * @param value The uUID to set.
       * @return This builder for chaining.
       */
      public Builder setUUID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uUID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string UUID = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUUID() {
        
        uUID_ = getDefaultInstance().getUUID();
        onChanged();
        return this;
      }
      /**
       * <code>string UUID = 6;</code>
       * @param value The bytes for uUID to set.
       * @return This builder for chaining.
       */
      public Builder setUUIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uUID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 7;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 7;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 7;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 7;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PlayerState)
    }

    // @@protoc_insertion_point(class_scope:PlayerState)
    private static final com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState();
    }

    public static com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerState>
        PARSER = new com.google.protobuf.AbstractParser<PlayerState>() {
      @java.lang.Override
      public PlayerState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025MinecraftPlayer.proto\"f\n\013PlayerState\022\t" +
      "\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\022\r\n\005pitch" +
      "\030\004 \001(\002\022\013\n\003yaw\030\005 \001(\002\022\014\n\004UUID\030\006 \001(\t\022\014\n\004nam" +
      "e\030\007 \001(\tB&\n$com.worldql.client.compiled_p" +
      "rotobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PlayerState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlayerState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerState_descriptor,
        new java.lang.String[] { "X", "Y", "Z", "Pitch", "Yaw", "UUID", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
