// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorldQLQuery.proto

package com.worldql.client.compiled_protobuf;

public final class WorldQLQuery {
  private WorldQLQuery() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WQLOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WQL)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.EchoRequest echo = 1;</code>
     * @return Whether the echo field is set.
     */
    boolean hasEcho();
    /**
     * <code>.EchoRequest echo = 1;</code>
     * @return The echo.
     */
    com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest getEcho();
    /**
     * <code>.EchoRequest echo = 1;</code>
     */
    com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequestOrBuilder getEchoOrBuilder();

    /**
     * <code>.PlayerState playerState = 2;</code>
     * @return Whether the playerState field is set.
     */
    boolean hasPlayerState();
    /**
     * <code>.PlayerState playerState = 2;</code>
     * @return The playerState.
     */
    com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState getPlayerState();
    /**
     * <code>.PlayerState playerState = 2;</code>
     */
    com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerStateOrBuilder getPlayerStateOrBuilder();

    public com.worldql.client.compiled_protobuf.WorldQLQuery.WQL.QueryCase getQueryCase();
  }
  /**
   * Protobuf type {@code WQL}
   */
  public static final class WQL extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WQL)
      WQLOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WQL.newBuilder() to construct.
    private WQL(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WQL() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WQL();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WQL(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest.Builder subBuilder = null;
              if (queryCase_ == 1) {
                subBuilder = ((com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest) query_).toBuilder();
              }
              query_ =
                  input.readMessage(com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest) query_);
                query_ = subBuilder.buildPartial();
              }
              queryCase_ = 1;
              break;
            }
            case 18: {
              com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.Builder subBuilder = null;
              if (queryCase_ == 2) {
                subBuilder = ((com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState) query_).toBuilder();
              }
              query_ =
                  input.readMessage(com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState) query_);
                query_ = subBuilder.buildPartial();
              }
              queryCase_ = 2;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.worldql.client.compiled_protobuf.WorldQLQuery.internal_static_WQL_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.worldql.client.compiled_protobuf.WorldQLQuery.internal_static_WQL_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.worldql.client.compiled_protobuf.WorldQLQuery.WQL.class, com.worldql.client.compiled_protobuf.WorldQLQuery.WQL.Builder.class);
    }

    private int queryCase_ = 0;
    private java.lang.Object query_;
    public enum QueryCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      ECHO(1),
      PLAYERSTATE(2),
      QUERY_NOT_SET(0);
      private final int value;
      private QueryCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static QueryCase valueOf(int value) {
        return forNumber(value);
      }

      public static QueryCase forNumber(int value) {
        switch (value) {
          case 1: return ECHO;
          case 2: return PLAYERSTATE;
          case 0: return QUERY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public QueryCase
    getQueryCase() {
      return QueryCase.forNumber(
          queryCase_);
    }

    public static final int ECHO_FIELD_NUMBER = 1;
    /**
     * <code>.EchoRequest echo = 1;</code>
     * @return Whether the echo field is set.
     */
    @java.lang.Override
    public boolean hasEcho() {
      return queryCase_ == 1;
    }
    /**
     * <code>.EchoRequest echo = 1;</code>
     * @return The echo.
     */
    @java.lang.Override
    public com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest getEcho() {
      if (queryCase_ == 1) {
         return (com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest) query_;
      }
      return com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest.getDefaultInstance();
    }
    /**
     * <code>.EchoRequest echo = 1;</code>
     */
    @java.lang.Override
    public com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequestOrBuilder getEchoOrBuilder() {
      if (queryCase_ == 1) {
         return (com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest) query_;
      }
      return com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest.getDefaultInstance();
    }

    public static final int PLAYERSTATE_FIELD_NUMBER = 2;
    /**
     * <code>.PlayerState playerState = 2;</code>
     * @return Whether the playerState field is set.
     */
    @java.lang.Override
    public boolean hasPlayerState() {
      return queryCase_ == 2;
    }
    /**
     * <code>.PlayerState playerState = 2;</code>
     * @return The playerState.
     */
    @java.lang.Override
    public com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState getPlayerState() {
      if (queryCase_ == 2) {
         return (com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState) query_;
      }
      return com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.getDefaultInstance();
    }
    /**
     * <code>.PlayerState playerState = 2;</code>
     */
    @java.lang.Override
    public com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerStateOrBuilder getPlayerStateOrBuilder() {
      if (queryCase_ == 2) {
         return (com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState) query_;
      }
      return com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (queryCase_ == 1) {
        output.writeMessage(1, (com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest) query_);
      }
      if (queryCase_ == 2) {
        output.writeMessage(2, (com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState) query_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (queryCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest) query_);
      }
      if (queryCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState) query_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.worldql.client.compiled_protobuf.WorldQLQuery.WQL)) {
        return super.equals(obj);
      }
      com.worldql.client.compiled_protobuf.WorldQLQuery.WQL other = (com.worldql.client.compiled_protobuf.WorldQLQuery.WQL) obj;

      if (!getQueryCase().equals(other.getQueryCase())) return false;
      switch (queryCase_) {
        case 1:
          if (!getEcho()
              .equals(other.getEcho())) return false;
          break;
        case 2:
          if (!getPlayerState()
              .equals(other.getPlayerState())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (queryCase_) {
        case 1:
          hash = (37 * hash) + ECHO_FIELD_NUMBER;
          hash = (53 * hash) + getEcho().hashCode();
          break;
        case 2:
          hash = (37 * hash) + PLAYERSTATE_FIELD_NUMBER;
          hash = (53 * hash) + getPlayerState().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.worldql.client.compiled_protobuf.WorldQLQuery.WQL parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.worldql.client.compiled_protobuf.WorldQLQuery.WQL parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.worldql.client.compiled_protobuf.WorldQLQuery.WQL parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.worldql.client.compiled_protobuf.WorldQLQuery.WQL parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.worldql.client.compiled_protobuf.WorldQLQuery.WQL parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.worldql.client.compiled_protobuf.WorldQLQuery.WQL parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.worldql.client.compiled_protobuf.WorldQLQuery.WQL parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.worldql.client.compiled_protobuf.WorldQLQuery.WQL parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.worldql.client.compiled_protobuf.WorldQLQuery.WQL parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.worldql.client.compiled_protobuf.WorldQLQuery.WQL parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.worldql.client.compiled_protobuf.WorldQLQuery.WQL parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.worldql.client.compiled_protobuf.WorldQLQuery.WQL parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.worldql.client.compiled_protobuf.WorldQLQuery.WQL prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WQL}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WQL)
        com.worldql.client.compiled_protobuf.WorldQLQuery.WQLOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.worldql.client.compiled_protobuf.WorldQLQuery.internal_static_WQL_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.worldql.client.compiled_protobuf.WorldQLQuery.internal_static_WQL_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.worldql.client.compiled_protobuf.WorldQLQuery.WQL.class, com.worldql.client.compiled_protobuf.WorldQLQuery.WQL.Builder.class);
      }

      // Construct using com.worldql.client.compiled_protobuf.WorldQLQuery.WQL.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        queryCase_ = 0;
        query_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.worldql.client.compiled_protobuf.WorldQLQuery.internal_static_WQL_descriptor;
      }

      @java.lang.Override
      public com.worldql.client.compiled_protobuf.WorldQLQuery.WQL getDefaultInstanceForType() {
        return com.worldql.client.compiled_protobuf.WorldQLQuery.WQL.getDefaultInstance();
      }

      @java.lang.Override
      public com.worldql.client.compiled_protobuf.WorldQLQuery.WQL build() {
        com.worldql.client.compiled_protobuf.WorldQLQuery.WQL result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.worldql.client.compiled_protobuf.WorldQLQuery.WQL buildPartial() {
        com.worldql.client.compiled_protobuf.WorldQLQuery.WQL result = new com.worldql.client.compiled_protobuf.WorldQLQuery.WQL(this);
        if (queryCase_ == 1) {
          if (echoBuilder_ == null) {
            result.query_ = query_;
          } else {
            result.query_ = echoBuilder_.build();
          }
        }
        if (queryCase_ == 2) {
          if (playerStateBuilder_ == null) {
            result.query_ = query_;
          } else {
            result.query_ = playerStateBuilder_.build();
          }
        }
        result.queryCase_ = queryCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.worldql.client.compiled_protobuf.WorldQLQuery.WQL) {
          return mergeFrom((com.worldql.client.compiled_protobuf.WorldQLQuery.WQL)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.worldql.client.compiled_protobuf.WorldQLQuery.WQL other) {
        if (other == com.worldql.client.compiled_protobuf.WorldQLQuery.WQL.getDefaultInstance()) return this;
        switch (other.getQueryCase()) {
          case ECHO: {
            mergeEcho(other.getEcho());
            break;
          }
          case PLAYERSTATE: {
            mergePlayerState(other.getPlayerState());
            break;
          }
          case QUERY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.worldql.client.compiled_protobuf.WorldQLQuery.WQL parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.worldql.client.compiled_protobuf.WorldQLQuery.WQL) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int queryCase_ = 0;
      private java.lang.Object query_;
      public QueryCase
          getQueryCase() {
        return QueryCase.forNumber(
            queryCase_);
      }

      public Builder clearQuery() {
        queryCase_ = 0;
        query_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest, com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest.Builder, com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequestOrBuilder> echoBuilder_;
      /**
       * <code>.EchoRequest echo = 1;</code>
       * @return Whether the echo field is set.
       */
      @java.lang.Override
      public boolean hasEcho() {
        return queryCase_ == 1;
      }
      /**
       * <code>.EchoRequest echo = 1;</code>
       * @return The echo.
       */
      @java.lang.Override
      public com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest getEcho() {
        if (echoBuilder_ == null) {
          if (queryCase_ == 1) {
            return (com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest) query_;
          }
          return com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest.getDefaultInstance();
        } else {
          if (queryCase_ == 1) {
            return echoBuilder_.getMessage();
          }
          return com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.EchoRequest echo = 1;</code>
       */
      public Builder setEcho(com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest value) {
        if (echoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          query_ = value;
          onChanged();
        } else {
          echoBuilder_.setMessage(value);
        }
        queryCase_ = 1;
        return this;
      }
      /**
       * <code>.EchoRequest echo = 1;</code>
       */
      public Builder setEcho(
          com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest.Builder builderForValue) {
        if (echoBuilder_ == null) {
          query_ = builderForValue.build();
          onChanged();
        } else {
          echoBuilder_.setMessage(builderForValue.build());
        }
        queryCase_ = 1;
        return this;
      }
      /**
       * <code>.EchoRequest echo = 1;</code>
       */
      public Builder mergeEcho(com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest value) {
        if (echoBuilder_ == null) {
          if (queryCase_ == 1 &&
              query_ != com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest.getDefaultInstance()) {
            query_ = com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest.newBuilder((com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest) query_)
                .mergeFrom(value).buildPartial();
          } else {
            query_ = value;
          }
          onChanged();
        } else {
          if (queryCase_ == 1) {
            echoBuilder_.mergeFrom(value);
          }
          echoBuilder_.setMessage(value);
        }
        queryCase_ = 1;
        return this;
      }
      /**
       * <code>.EchoRequest echo = 1;</code>
       */
      public Builder clearEcho() {
        if (echoBuilder_ == null) {
          if (queryCase_ == 1) {
            queryCase_ = 0;
            query_ = null;
            onChanged();
          }
        } else {
          if (queryCase_ == 1) {
            queryCase_ = 0;
            query_ = null;
          }
          echoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.EchoRequest echo = 1;</code>
       */
      public com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest.Builder getEchoBuilder() {
        return getEchoFieldBuilder().getBuilder();
      }
      /**
       * <code>.EchoRequest echo = 1;</code>
       */
      @java.lang.Override
      public com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequestOrBuilder getEchoOrBuilder() {
        if ((queryCase_ == 1) && (echoBuilder_ != null)) {
          return echoBuilder_.getMessageOrBuilder();
        } else {
          if (queryCase_ == 1) {
            return (com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest) query_;
          }
          return com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.EchoRequest echo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest, com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest.Builder, com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequestOrBuilder> 
          getEchoFieldBuilder() {
        if (echoBuilder_ == null) {
          if (!(queryCase_ == 1)) {
            query_ = com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest.getDefaultInstance();
          }
          echoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest, com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest.Builder, com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequestOrBuilder>(
                  (com.worldql.client.compiled_protobuf.EchoRequestOuterClass.EchoRequest) query_,
                  getParentForChildren(),
                  isClean());
          query_ = null;
        }
        queryCase_ = 1;
        onChanged();;
        return echoBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState, com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.Builder, com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerStateOrBuilder> playerStateBuilder_;
      /**
       * <code>.PlayerState playerState = 2;</code>
       * @return Whether the playerState field is set.
       */
      @java.lang.Override
      public boolean hasPlayerState() {
        return queryCase_ == 2;
      }
      /**
       * <code>.PlayerState playerState = 2;</code>
       * @return The playerState.
       */
      @java.lang.Override
      public com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState getPlayerState() {
        if (playerStateBuilder_ == null) {
          if (queryCase_ == 2) {
            return (com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState) query_;
          }
          return com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.getDefaultInstance();
        } else {
          if (queryCase_ == 2) {
            return playerStateBuilder_.getMessage();
          }
          return com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.getDefaultInstance();
        }
      }
      /**
       * <code>.PlayerState playerState = 2;</code>
       */
      public Builder setPlayerState(com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState value) {
        if (playerStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          query_ = value;
          onChanged();
        } else {
          playerStateBuilder_.setMessage(value);
        }
        queryCase_ = 2;
        return this;
      }
      /**
       * <code>.PlayerState playerState = 2;</code>
       */
      public Builder setPlayerState(
          com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.Builder builderForValue) {
        if (playerStateBuilder_ == null) {
          query_ = builderForValue.build();
          onChanged();
        } else {
          playerStateBuilder_.setMessage(builderForValue.build());
        }
        queryCase_ = 2;
        return this;
      }
      /**
       * <code>.PlayerState playerState = 2;</code>
       */
      public Builder mergePlayerState(com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState value) {
        if (playerStateBuilder_ == null) {
          if (queryCase_ == 2 &&
              query_ != com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.getDefaultInstance()) {
            query_ = com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.newBuilder((com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState) query_)
                .mergeFrom(value).buildPartial();
          } else {
            query_ = value;
          }
          onChanged();
        } else {
          if (queryCase_ == 2) {
            playerStateBuilder_.mergeFrom(value);
          }
          playerStateBuilder_.setMessage(value);
        }
        queryCase_ = 2;
        return this;
      }
      /**
       * <code>.PlayerState playerState = 2;</code>
       */
      public Builder clearPlayerState() {
        if (playerStateBuilder_ == null) {
          if (queryCase_ == 2) {
            queryCase_ = 0;
            query_ = null;
            onChanged();
          }
        } else {
          if (queryCase_ == 2) {
            queryCase_ = 0;
            query_ = null;
          }
          playerStateBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.PlayerState playerState = 2;</code>
       */
      public com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.Builder getPlayerStateBuilder() {
        return getPlayerStateFieldBuilder().getBuilder();
      }
      /**
       * <code>.PlayerState playerState = 2;</code>
       */
      @java.lang.Override
      public com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerStateOrBuilder getPlayerStateOrBuilder() {
        if ((queryCase_ == 2) && (playerStateBuilder_ != null)) {
          return playerStateBuilder_.getMessageOrBuilder();
        } else {
          if (queryCase_ == 2) {
            return (com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState) query_;
          }
          return com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.getDefaultInstance();
        }
      }
      /**
       * <code>.PlayerState playerState = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState, com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.Builder, com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerStateOrBuilder> 
          getPlayerStateFieldBuilder() {
        if (playerStateBuilder_ == null) {
          if (!(queryCase_ == 2)) {
            query_ = com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.getDefaultInstance();
          }
          playerStateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState, com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState.Builder, com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerStateOrBuilder>(
                  (com.worldql.client.compiled_protobuf.MinecraftPlayer.PlayerState) query_,
                  getParentForChildren(),
                  isClean());
          query_ = null;
        }
        queryCase_ = 2;
        onChanged();;
        return playerStateBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WQL)
    }

    // @@protoc_insertion_point(class_scope:WQL)
    private static final com.worldql.client.compiled_protobuf.WorldQLQuery.WQL DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.worldql.client.compiled_protobuf.WorldQLQuery.WQL();
    }

    public static com.worldql.client.compiled_protobuf.WorldQLQuery.WQL getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WQL>
        PARSER = new com.google.protobuf.AbstractParser<WQL>() {
      @java.lang.Override
      public WQL parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WQL(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WQL> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WQL> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.worldql.client.compiled_protobuf.WorldQLQuery.WQL getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WQL_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WQL_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022WorldQLQuery.proto\032\021EchoRequest.proto\032" +
      "\025MinecraftPlayer.proto\"Q\n\003WQL\022\034\n\004echo\030\001 " +
      "\001(\0132\014.EchoRequestH\000\022#\n\013playerState\030\002 \001(\013" +
      "2\014.PlayerStateH\000B\007\n\005queryB&\n$com.worldql" +
      ".client.compiled_protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.worldql.client.compiled_protobuf.EchoRequestOuterClass.getDescriptor(),
          com.worldql.client.compiled_protobuf.MinecraftPlayer.getDescriptor(),
        });
    internal_static_WQL_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WQL_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WQL_descriptor,
        new java.lang.String[] { "Echo", "PlayerState", "Query", });
    com.worldql.client.compiled_protobuf.EchoRequestOuterClass.getDescriptor();
    com.worldql.client.compiled_protobuf.MinecraftPlayer.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
